# generated by datamodel-codegen:
#   filename:  Swagger_v5.YAML
#   timestamp: 2026-05-03T14:24:52+00:00

from __future__ import annotations

from datetime import date, datetime, time
from enum import Enum
from typing import List, Optional, Union

from pydantic import AnyUrl, BaseModel, EmailStr, Field, SecretStr


class Categoria(Enum):
    comun = 'comun'
    especial = 'especial'
    plata = 'plata'
    oro = 'oro'
    platino = 'platino'


class Moneda(Enum):
    ARS = 'ARS'
    USD = 'USD'


class RegistroPaso1(BaseModel):
    documento: str = Field(..., example='35123456')
    nombre: str = Field(..., example='Juan')
    apellido: str = Field(..., example='Perez')
    email: EmailStr = Field(..., example='juan.perez@email.com')
    telefono: Optional[str] = Field(None, example='+54 11 5555-5555')
    direccion: str = Field(..., example='Av. Corrientes 1234, CABA')
    numeroPais: int = Field(..., example=1)
    fotoFrente: AnyUrl
    fotoDorso: AnyUrl


class RegistroPaso2(BaseModel):
    token: str = Field(..., description='Token recibido por email')
    password: SecretStr


class VerifyEmail(BaseModel):
    token: str


class ForgotPassword(BaseModel):
    email: EmailStr


class ResetPassword(BaseModel):
    token: str
    newPassword: SecretStr


class Login(BaseModel):
    documento: str = Field(..., example='35123456')
    password: SecretStr = Field(..., example='MiClaveSecreta123')


class TokenResponse(BaseModel):
    access_token: Optional[str] = Field(
        None, example='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
    )
    token_type: Optional[str] = Field(None, example='bearer')


class Admitido(Enum):
    si = 'si'
    no = 'no'


class EstadoRegistro(Enum):
    pendiente = 'pendiente'
    aprobado = 'aprobado'
    rechazado = 'rechazado'


class Usuario(BaseModel):
    id: Optional[int] = None
    documento: Optional[str] = None
    nombre: Optional[str] = None
    apellido: Optional[str] = None
    email: Optional[EmailStr] = None
    direccion: Optional[str] = None
    telefono: Optional[str] = None
    foto: Optional[AnyUrl] = Field(
        None, example='https://storage.example.com/users/35123456/photo.jpg'
    )
    numeroPais: Optional[int] = None
    admitido: Optional[Admitido] = None
    estadoRegistro: Optional[EstadoRegistro] = None
    categoria: Optional[Categoria] = None
    validatedPaymentDiversity: Optional[int] = Field(
        None, description='Cantidad de tipos distintos de medios de pago validados.'
    )
    multaActiva: Optional[bool] = Field(
        None, description='Si el usuario tiene una multa del 10% sin pagar.'
    )
    bloqueado: Optional[bool] = Field(
        None, description='Si el usuario quedo bloqueado por incumplimiento.'
    )
    fotoFrente: Optional[str] = None
    fotoDorso: Optional[str] = None


class UsuarioUpdate(BaseModel):
    nombre: Optional[str] = None
    apellido: Optional[str] = None
    direccion: Optional[str] = None
    telefono: Optional[str] = None
    foto: Optional[AnyUrl] = None


class UsuarioVerificacion(BaseModel):
    admitido: bool
    categoria: Optional[Categoria] = None
    motivoRechazo: Optional[str] = None


class UpdateCategoriaRequest(BaseModel):
    categoria: Categoria


class AutoCategoryResult(BaseModel):
    categoriaAnterior: Categoria
    categoriaNueva: Categoria
    motivo: str
    upgraded: bool = Field(False)


class UsuarioMetricas(BaseModel):
    totalSubastasParticipadas: Optional[int] = Field(None, example=15)
    totalSubastasGanadas: Optional[int] = Field(None, example=4)
    porcentajeExito: Optional[float] = Field(None, example=26.6)
    totalPujasRealizadas: Optional[int] = Field(None, example=120)
    montoTotalOfertado: Optional[float] = Field(None, example=350000.5)
    montoTotalPagado: Optional[float] = Field(None, example=120000.0)
    categoriasParticipadas: Optional[List[Categoria]] = None
    ultimaParticipacion: Optional[datetime] = None


class MediosDePago(Enum):
    tarjeta_credito = 'tarjeta_credito'
    cuenta_bancaria = 'cuenta_bancaria'
    cheque_certificado = 'cheque_certificado'


class EstadoVerificacion(Enum):
    pendiente = 'pendiente'
    validado = 'validado'
    rechazado = 'rechazado'


class MedioPago(BaseModel):
    id: Optional[int] = None
    tipo: Optional[MediosDePago] = None
    ultimos_digitos: Optional[str] = Field(None, example='4321')
    estadoVerificacion: Optional[EstadoVerificacion] = None
    moneda: Optional[Moneda] = None
    limiteReservado: Optional[float] = Field(None, example=50000.0)
    paisBanco: Optional[str] = Field(None, example='AR')
    esCuentaReceptora: Optional[bool] = Field(
        None, description='Indica si esta cuenta se usa para recibir pagos.'
    )


class MedioPagoInput(BaseModel):
    tipo: MediosDePago
    datos_encriptados: str = Field(
        ..., description='Token generado por la pasarela de pagos.'
    )
    moneda: Moneda
    limiteReservado: Optional[float] = None
    paisBanco: Optional[str] = None
    esCuentaReceptora: Optional[bool] = None


class MedioPagoUpdate(BaseModel):
    limiteReservado: Optional[float] = None
    esCuentaReceptora: Optional[bool] = None


class EstadoVerificacionMedioPagoInput(Enum):
    validado = 'validado'
    rechazado = 'rechazado'


class MedioPagoVerificacion(BaseModel):
    estadoVerificacion: EstadoVerificacionMedioPagoInput


class EstadoMulta(Enum):
    pendiente = 'pendiente'
    pagada = 'pagada'


class Multa(BaseModel):
    id: Optional[int] = None
    importe: Optional[float] = None
    estado: Optional[EstadoMulta] = None
    fechaLimite: Optional[datetime] = None
    motivo: Optional[str] = None


class MultaPagoRequest(BaseModel):
    multaId: int
    medioPagoId: int


class TipoNotificacion(Enum):
    pago = 'pago'
    subasta = 'subasta'
    sistema = 'sistema'


class Notificacion(BaseModel):
    id: Optional[int] = None
    tipo: Optional[TipoNotificacion] = None
    mensaje: Optional[str] = None
    fechaHora: Optional[datetime] = None
    leida: Optional[bool] = None


class EstadoSubasta(Enum):
    abierta = 'abierta'
    cerrada = 'cerrada'


class SubastaListado(BaseModel):
    id: Optional[int] = None
    fecha: Optional[date] = None
    hora: Optional[time] = None
    estado: Optional[EstadoSubasta] = None
    categoria: Optional[Categoria] = None
    ubicacion: Optional[str] = None
    moneda: Optional[Moneda] = None


class SubastaListadoPublico(SubastaListado):
    pass


class Subastado(Enum):
    si = 'si'
    no = 'no'


class ItemCatalogo(BaseModel):
    id: Optional[int] = None
    descripcion: Optional[str] = Field(None, example='Juego de Te de 18 piezas antiguo')
    precioBase: Optional[float] = Field(
        None, description='Solo visible si el usuario cumple los requisitos.'
    )
    mejorOfertaActual: Optional[float] = None
    limiteMinimo: Optional[float] = Field(
        None, description='Mejor oferta + 1% del valor base (si aplica).'
    )
    limiteMaximo: Optional[float] = Field(
        None, description='Mejor oferta + 20% del valor base (si aplica).'
    )
    subastado: Optional[Subastado] = None
    fotos: Optional[List[AnyUrl]] = None


class ItemCatalogoPublico(BaseModel):
    id: Optional[int] = None
    descripcion: Optional[str] = None
    mejorOfertaActual: Optional[float] = None
    subastado: Optional[Subastado] = None
    fotos: Optional[List[AnyUrl]] = None


class PujaRequest(BaseModel):
    importe: float = Field(
        ..., description='Monto de la oferta realizada.', example=15150.0
    )


class PujaResponse(BaseModel):
    pujaId: Optional[int] = None
    mejorOfertaActual: Optional[float] = None
    limiteMinimo: Optional[float] = None
    limiteMaximo: Optional[float] = None
    moneda: Optional[Moneda] = None
    esGanadoraParcial: Optional[bool] = None


class CodigoGarantiaInsuficiente(Enum):
    GARANTIA_INSUFICIENTE = 'GARANTIA_INSUFICIENTE'


class GarantiaInsuficienteError(BaseModel):
    codigo: Optional[CodigoGarantiaInsuficiente] = None
    mensaje: Optional[str] = None
    garantiaDisponible: Optional[float] = Field(
        None,
        description='Garantia aun disponible antes de registrar la puja candidata.',
    )
    exposicionActual: Optional[float] = Field(
        None,
        description='Pagos pendientes mas pujas ganadoras parciales activas antes de la candidata.',
    )
    importeRequerido: Optional[float] = Field(
        None,
        description='Exposicion adicional que agregaria la puja candidata.',
    )
    moneda: Optional[Moneda] = None


class Puja(BaseModel):
    id: Optional[int] = None
    usuarioId: Optional[int] = Field(
        None, description='ID del usuario que realizo la puja'
    )
    itemId: Optional[int] = Field(None, description='ID del item subastado')
    importe: Optional[float] = Field(None, example=15200.5)
    moneda: Optional[Moneda] = None
    fechaHora: Optional[datetime] = Field(None, example='2026-04-27T21:30:00Z')
    esGanadoraParcial: Optional[bool] = Field(
        None, description='Indica si esta puja fue la mejor en ese momento'
    )


class ModoEntrega(Enum):
    envio = 'envio'
    retiro = 'retiro'


class EstadoPago(Enum):
    pendiente = 'pendiente'
    pagado = 'pagado'
    vencido = 'vencido'


class Pago(BaseModel):
    id: Optional[int] = None
    subastaId: Optional[int] = None
    usuarioId: Optional[int] = None
    totalPujado: Optional[float] = None
    comision: Optional[float] = None
    costoEnvio: Optional[float] = None
    totalFinal: Optional[float] = None
    moneda: Optional[Moneda] = None
    modoEntrega: Optional[ModoEntrega] = None
    estado: Optional[EstadoPago] = None
    fechaLimitePago: Optional[datetime] = None


class PagoPendienteItem(BaseModel):
    itemId: Optional[int] = None
    productoId: Optional[int] = None
    descripcion: Optional[str] = None
    importe: Optional[float] = None
    comision: Optional[float] = None


class PagoPendientePerfil(Pago):
    subastaFecha: Optional[date] = None
    subastaHora: Optional[time] = None
    subastaUbicacion: Optional[str] = None
    items: Optional[List[PagoPendienteItem]] = None


class PagoRequest(BaseModel):
    medioPagoId: int
    modoEntrega: ModoEntrega
    direccionEnvio: Optional[str] = None
    aceptaPerderSeguro: Optional[bool] = None


class EstadoSesionSubasta(Enum):
    activa = 'activa'
    finalizada = 'finalizada'


class SesionSubasta(BaseModel):
    id: Optional[int] = None
    subastaId: Optional[int] = None
    usuarioId: Optional[int] = None
    estado: Optional[EstadoSesionSubasta] = None
    fechaHoraInicio: Optional[datetime] = None


class TipoStreamEvent(Enum):
    puja = 'puja'
    item = 'item'
    cierre = 'cierre'


class ItemCerradoStreamData(BaseModel):
    id: Optional[int] = None
    productoId: Optional[int] = None
    precioBase: Optional[float] = None
    pujaId: Optional[int] = None
    clienteGanador: Optional[int] = None
    importe: Optional[float] = None


class ItemStreamData(BaseModel):
    itemCerrado: Optional[ItemCerradoStreamData] = None
    itemActivo: Optional[ItemCatalogo] = None
    itemsPendientes: Optional[int] = None
    subastaCerrada: Optional[bool] = None


class CierreStreamData(BaseModel):
    message: Optional[str] = None
    itemsCerrados: Optional[int] = None


class StreamEvent(BaseModel):
    type: Optional[TipoStreamEvent] = None
    fechaHora: Optional[datetime] = None
    data: Optional[Union[Puja, ItemCatalogo, ItemStreamData, CierreStreamData]] = None


class ArticuloInput(BaseModel):
    descripcion: str = Field(..., example='Reloj antiguo del siglo XIX')
    historia: Optional[str] = Field(
        None, description='Informacion historica o contexto del objeto'
    )
    artista: Optional[str] = Field(None, description='Nombre del artista o disenador')
    fechaCreacion: Optional[date] = None
    precioSugeridoUsuario: Optional[float] = Field(
        None, description='Valor estimado por el usuario (solo referencia)'
    )
    fotos: List[AnyUrl] = Field(..., min_items=6)
    documentacionOrigen: Optional[List[AnyUrl]] = Field(
        None, description='Documentacion que acredita el origen del articulo'
    )
    esPropietario: bool = Field(..., description='Declaracion de propiedad del bien')
    declaraOrigenLicito: bool = Field(..., description='Declaracion de origen licito')


class EstadoArticulo(Enum):
    pendiente = 'pendiente'
    en_inspeccion = 'en_inspeccion'
    aprobado = 'aprobado'
    rechazado = 'rechazado'
    devuelto = 'devuelto'


class EstadoEvaluacionArticulo(Enum):
    aprobado = 'aprobado'
    rechazado = 'rechazado'


class ArticuloEvaluacion(BaseModel):
    estado: EstadoEvaluacionArticulo
    motivoRechazo: Optional[str] = None
    precioBasePropuesto: Optional[float] = None
    comisionPropuesta: Optional[float] = None
    subastaSugeridaId: Optional[int] = None


class AceptarTasacionRequest(BaseModel):
    acepta: bool


class Seguro(BaseModel):
    poliza: Optional[str] = Field(None, example='POL-123456')
    compania: Optional[str] = None
    montoAsegurado: Optional[float] = Field(None, example=50000)


class SeguroAumentoRequest(BaseModel):
    montoNuevo: float


class SubastaCreate(BaseModel):
    fecha: date
    hora: time
    categoria: Categoria
    moneda: Moneda
    subastadorId: Optional[int] = None
    ubicacion: Optional[str] = None
    capacidadAsistentes: Optional[int] = None
    tieneDeposito: Optional[bool] = None
    seguridadPropia: Optional[bool] = None


class CatalogoItemInput(BaseModel):
    productoId: Optional[int] = None
    articuloId: Optional[int] = None
    precioBase: float
    comision: float


class SubastaDetalle(SubastaListado):
    catalogo: Optional[List[ItemCatalogo]] = None
    tieneDeuda: Optional[bool] = None


class SubastaDetallePublica(SubastaListadoPublico):
    catalogo: Optional[List[ItemCatalogoPublico]] = None


class Articulo(BaseModel):
    id: Optional[int] = None
    descripcion: Optional[str] = None
    precioSugeridoUsuario: Optional[float] = None
    precioBasePropuesto: Optional[float] = None
    comisionPropuesta: Optional[float] = None
    tasacionAceptada: Optional[bool] = None
    historia: Optional[str] = None
    artista: Optional[str] = None
    fechaCreacion: Optional[date] = None
    estado: Optional[EstadoArticulo] = None
    motivoRechazo: Optional[str] = None
    fechaEnvio: Optional[datetime] = None
    fotos: Optional[List[AnyUrl]] = None
    ubicacion: Optional[str] = Field(None, example='Deposito CABA')
    seguro: Optional[Seguro] = None
    subastaId: Optional[int] = None
    subastaFecha: Optional[date] = None
    subastaHora: Optional[time] = None
    subastaEstado: Optional[str] = None
